### ISSUE TITLE
configurable table names

### ISSUE THREAD

**Issue by basz** [TomHAnderson/zf-oauth2-doctrine#20]
Hi, I'm not sure if you are willing to persui this but in IMO think I configurable tables names is a feature people would want. As a personal preference I tend to keep all table names (and column names) in lower case and functional grouped (prefixing 'oauth2' instead of appending)

Doing a little research I learned that to do this one should write an EventListener and since one is already present in this project it not hard to add this.

table names of the main entities are easy. Those of the join tables are a little harder (need to think up a good config name). But I've got a prototype running here.

So, my question. Would you consider accepting a PR for this? If not - no problem - i'll write my own EventListener.

**Comment by basz** [comment]
This is what I did : https://gist.github.com/basz/56aef5773154a5687b77 based on PR #19 

- added missing entities to switch to only configure tableName
- added a 'associations_override' key to ['scope_entity']['additional_mapping_data'] to override the join table mappings

**Comment by TomHAnderson** [comment]
I'm open to review any PR submitted.

I haven't created a Doctrine entity collection like this before with dynamic joins (but I've created something close to it & I think this is implemented better than that collection of interfaces) and I think it's a very good pattern.  My concern is whether the simplicity of bringing in tables to an existing project is being overruled by your lack of constant naming conventions.  That is, your naming strategy for your user table is `strtolower(tablename) . '_id';` while the rest of the tables here are just `id`.  So you're deliberately not following a single naming strategy across your metadata which this repository suggests as `id`.  

I liked your first table renaming https://gist.github.com/basz/f6160c207c81742b949b because it's decoupled from the suggested naming here.  associations_override is also custom metadata which doesn't need to be configured at the same time as the join tables.  

My take here is Doctrine allows a lot of custom metadata configuration and trying to support everything it can do isn't in the spirit of this project.  So I welcome your changes but I'm leaning towards a `Tips & Tricks` section in the README.md with a link to instructions in `/docs` for doing what you've assembled but not incorporating direct support for it.  Where direct support is required like `additional_mapping_data` in order to create the dynamic joins at runtime I'm very much in favor of including with the distributed code.

**Comment by basz** [comment]
As for https://gist.github.com/basz/f6160c207c81742b949b this is just half the story. The join tables aren't renamed yet. Hence the associations_override. I agree a separate event subscriber would be best, so I'll probably try to write something up to be able to change table names as I really like to be able to do that.

Further please note that it is not *my* naming strategy but one that comes with ZfcUser. I'm just saying I am not *deliberately* misbehaving :-) They use user_id as PK and I am just trying to whip that thing into playing nice. I should probably give up and simply create a new entity with the correct ZfcUser interfaces (re)implemented instead of extending. Just hope ZfcUserDoctrineOrm does not care to much...

ps. where can I go best for simple support questions as I do have a few... (irc#apigility, google groups?) I'm aware it's still prerelease...

**Comment by TomHAnderson** [comment]
You've typed more about this than anyone else.  I'm glad you're passionate about using it.  
I'll be in freenode#apigility where maybe we can get some heads turned at the idea.

**Comment by basz** [comment]
hehe ... check this : http://github.com/basz/zf-oauth2-doctrine-mutatetablenames

**Comment by TomHAnderson** [comment]
http://github.com/basz/zf-oauth2-doctrine-mutatetablenames will be the repository for this enhancement.  If you feel these repos should be one in the same please commet.
